### ISSUE TITLE
not being accessible

### ISSUE THREAD

**Issue by vama-stack** [jakecrowley/Google-Meet-Attendance#1]
please guide me with this issue. whenever icon is clicked of google meet attendance, instead of drop down option the dialogue box appears created by with tittle and some instruction when followed the instruction still not accessible, as such
![Screenshot (29)](https://user-images.githubusercontent.com/68316926/87518472-f2915f80-c69d-11ea-9fc6-d6535bf339ad.png)

**Comment by jakecrowley** [comment]
Hi, you save the attendance by right clicking in an active Google Meet session and clicking the "Save Attendance" button in the context menu.
